name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_webservice
version: 0.0.1
repository: https://github.com/QasimWaheed/flutter_google_places

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^4.2.3
  google_maps_webservice:
    git:
      url: https://github.com/QasimWaheed/google_maps_webservice_v2
  http: ^1.2.2
  rxdart: ^0.28.0

dependency_overrides:
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  flutter_lints: ^4.0.0

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
